// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next"; // Import metadata type for typing the metadata object
import { Geist, Geist_Mono } from "next/font/google"; // Import Google Fonts using next/font
import "./globals.css"; // Import global CSS for consistent styling


<link rel="icon" href="/favicon.ico" />


// Define font configurations with variables for easy reference in styles
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the page, useful for SEO and browser tabs
export const metadata: Metadata = {
  title: "Luggage Storage Online",
  description: "Store your luggage",
};

// Root layout component, wraps all pages with the global layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Add header, footer, or global navigation here if needed */}
        <main>{children}</main>
      </body>
    </html>
  );
}